### ISSUE TITLE
VCU Task List

### ISSUE THREAD

**Issue by kantrveysel** [kantrveysel/YTURacing-E-PowerTrain-2021#3]
- [ ] Araç kapatıldıktan sonra tekrar açılmıyor
- [ ] Display ile haberleşme [ _CANBus_ ]
- [ ] BMS ile haberleşme [ _Serial ( RS232 )_ ]
- [ ] APPS boşluklu
- [ ] Max güç 80 kW sınırı

> R2D button displaya aktarılarak CANBus kullanılarak haberleşmesi

> BMS verileri toparlanıp tekrar CANBus'a yansıtılacak adresslenmesi ve sistemize edilmesi gerekiyor

>
